# Generated by Django 4.0.4 on 2022-05-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='modified_field',
            new_name='modified_date',
        ),
    ]
