# Generated by Django 4.0.4 on 2022-05-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
        ('store', '0002_rename_modified_field_store_modified_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Product',
        ),
    ]
