# Generated by Django 4.0.4 on 2022-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
